name: Daily Commit

on:
  schedule:
    - cron: '30 2 * * *'  # Runs daily at 2:30 AM UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "23f3001400@ds.study.iitm.ac.in"

      - name: Make changes
        run: |
          echo "Last run: $(date)" > last_run.txt

      - name: Commit changes
        run: |
          git add .
          git commit -m "Automated daily commit $(date)"
          git push
